server:
  port: 8080

spring:
  datasource:
    # 建议改为绝对路径，避免切换目录后“看不到数据”
    url: jdbc:h2:file:${user.home}/tsm-data/tsm;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.tsm: debug
    org.springframework.web: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace